{{- if and .Values.dataPVC.enabled .Values.dataPVC.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-data" (include "kubetty.fullname" .)) .Values.dataPVC.name }}
  labels:
    app.kubernetes.io/name: {{ include "kubetty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{- range .Values.dataPVC.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.dataPVC.size }}
  {{- if .Values.dataPVC.storageClass }}
  storageClassName: {{ .Values.dataPVC.storageClass }}
  {{- end }}
{{- end }}
