{{- if and .Values.homePVC.enabled .Values.homePVC.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-home" (include "kubetty.fullname" .)) .Values.homePVC.name }}
  labels:
    app.kubernetes.io/name: {{ include "kubetty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{- range .Values.homePVC.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.homePVC.size }}
  {{- if .Values.homePVC.storageClass }}
  storageClassName: {{ .Values.homePVC.storageClass }}
  {{- end }}
{{- end }}
