apiVersion: v2
name: kubetty-project
version: 0.7.3
appVersion: "0.7.3"
description: KubeTTY Project Pod - Single-user terminal environment accessed via gateway
keywords:
  - kubetty
  - project
  - terminal
  - kubernetes
  - pty
home: https://github.com/supporttools/KubeTTY
maintainers:
  - name: SupportTools
    url: https://github.com/supporttools
